# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 652)
        MainWindow.setMinimumSize(QtCore.QSize(1320, 652))
        MainWindow.setMaximumSize(QtCore.QSize(1320, 652))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 1281, 611))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 75 28pt \"Cantarell\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        self.start.setMinimumSize(QtCore.QSize(0, 45))
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.start_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.start_2.setMinimumSize(QtCore.QSize(0, 45))
        self.start_2.setObjectName("start_2")
        self.horizontalLayout.addWidget(self.start_2)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setMinimumSize(QtCore.QSize(0, 45))
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_3.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_8.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_9.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(237, 16777215))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.textEdit_3 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_5.addWidget(self.textEdit_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_5.addWidget(self.textEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setStyleSheet("font: 75 14pt \"Open Sans Condensed\";\n"
"")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 270))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 110))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_2.setBuddy(self.start)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanner_Blueborne"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Scanner Blueborne</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Запустить сканер"))
        self.start.setText(_translate("MainWindow", "Автоматический запуск"))
        self.start_2.setText(_translate("MainWindow", "Ручной запуск"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Результат по классу (все уст-ва):</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Результат по </span></p><p><span style=\" font-size:10pt;\">CVE-2017-0785 (моб. уст-ва):</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Результат по </span></p><p><span style=\" font-size:10pt;\">CVE-2017-1000250 (комп-ры):</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "CVE-2017-0785"))
        self.pushButton.setText(_translate("MainWindow", "Эксплойт"))
        self.label_7.setText(_translate("MainWindow", "CVE-2017-1000250"))
        self.pushButton_2.setText(_translate("MainWindow", "Эксплойт"))
        self.label_10.setText(_translate("MainWindow", "CVE-2017-0781 (Атака) "))
        self.pushButton_3.setText(_translate("MainWindow", "Эксплойт"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/newPrefix/imgonline-com-ua-Resize-R3o64mqMxjjBjd8o.jpg\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Работа сделана:</p><p>курсантами 651/1 учебной группы</p><p>ефрейтором Соболевым А.А.</p><p>сержантом Ратушняком М.А.</p></body></html>"))


#import src_rc
